In [1]:
import numpy as np

In [ ]:

def m_init(shape , value = 0):
    '''
    extra point in the begining of pandas session 
    '''
    return np.full(shape,value)

In [5]:
m_init((3,3))

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [7]:
v = np.array([1,2,3,4])
print(v.ndim)
print(v.shape)
m = np.array([[1,2,3],
              [4,5,6],
              [6,7,8]
])
print(m.ndim)
print(m.shape)

1
(4,)
2
(3, 3)


In [8]:
vec = np.array([1,2,3,4,5,6])
mat = vec.reshape(3,2)
mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
vec = np.array([1,2,3,4])
mat = vec.reshape(vec.shape[0],1)
print(mat)

[[1]
 [2]
 [3]
 [4]]


In [14]:
def array_reshape(arr, rows = -1, cols= -1):
    try:
        arr = np.array(arr)
        return arr.reshape(rows, cols)
    except (TypeError, ValueError) as e:
        raise ValueError(f"invalid reshape operation: {e}")


In [15]:
vec = [1,2,3,4,5,6]
array_reshape(vec, 2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
# object-> string-> float-> int-> bool 
mat = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(mat.dtype)


int64


In [17]:
def covert_dtype(arr, dtype):
    try:
        arr = np.array(arr)
        return arr.astype(dtype)
    except (TypeError, ValueError) as e:
        raise ValueError(f"invalid reshape operation: {e}")


In [19]:
mat = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

m[1,2]
m[1:3, 0:2]

array([[4, 5],
       [6, 7]])

In [21]:
mat = np.zeros((3,4))
mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
mat = np.ones((3,4))
mat

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
mat = np.full((3,4),7)
mat

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [28]:
mat = np.empty((3,3))
mat

array([[4.9e-324, 9.9e-324, 1.5e-323],
       [2.0e-323, 2.5e-323, 3.0e-323],
       [3.5e-323, 4.0e-323, 4.4e-323]])

In [30]:
angels= np.arange(0,361,90)
angels

array([  0,  90, 180, 270, 360])

In [31]:
vec = np.linspace(0 ,10 , num = 10)
vec

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [33]:
i = np.identity(3, dtype= 'int64')